name: docker

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string

env:
  IMG_TAG: 15.2-bullseye

jobs:
  build_img:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: get image name
        id: get_img_name
        run: |
          dir_name=$(basename "${{ inputs.context }}")
          img_name="${dir_name#"docker-"}"
          echo "img_name=${img_name}" >> "$GITHUB_OUTPUT"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4.6.0
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ steps.get_img_name.outputs.img_name }}
          labels:
            maintainer=sksat
          flavor: |
            latest=auto
          tags: |
            enable={{is_default_branch}},type=raw,value=${{ env.IMG_TAG }}
            enable={{is_default_branch}},prefix=${{ env.IMG_TAG }}-,type=sha
            enable={{is_default_branch}},prefix=${{ env.IMG_TAG }}-,type=sha,format=long
            prefix=${{ env.IMG_TAG }}-pr-,type=ref,event=pr

      - name: Login to ghcr.io
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4.2.1
        with:
          context: ${{ inputs.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
