name: earthly-debian

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string

jobs:
  gen_debian_base_matrix:
    outputs:
      base_tag: ${{ steps.base-matrix.outputs.matrix }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

    - name: generate build image matrix
      id: base-matrix
      run: |
        {
          echo -n "matrix="
          yq -o=json .debian ./base-images.yaml | tr -d '\n'
        } >> "$GITHUB_OUTPUT"

  build_debian:
    name: "debian:${{ matrix.base_tag }}"
    needs: gen_debian_base_matrix

    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        base_tag: ${{ fromJSON(needs.gen_debian_base_matrix.outputs.base_tag) }}
        arch: ["x64"]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

    - name: get image-name
      id: image-name
      run: |
        src_dir="${{ inputs.context }}"
        src_dir=${src_dir#"./"}
        image_name=${src_dir#"earthly-"}
        echo "image-name: ${image_name}"
        echo "name=${image_name}" >> "$GITHUB_OUTPUT"

    - uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.name }},enable=true
        flavor: |
          latest=auto
        tags: |
          enable={{is_default_branch}},type=sha
          type=ref,event=pr

    - uses: earthly/actions-setup@43211c7a0eae5344d6d79fb4aaf209c8f8866203 # v1.0.13
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to ghcr.io
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
      if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push container image
      env:
        EARTHLY_PUSH: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        EARTHLY_REMOTE_CACHE: ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.name }}:cache-${{ matrix.base_tag }}-${{ matrix.arch }}
      working-directory: ${{ inputs.context }}
      run: |
        earthly +docker \
         --BASE_TAG=${{ matrix.base_tag }}  --DOCKER_META_VERSION=${{ steps.meta.outputs.version }}
