name: earthly-debian

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string

jobs:
  gen_debian_base_matrix:
    outputs:
      base_tag: ${{ steps.base-matrix.outputs.matrix }}

    runs-on: ubuntu-latest

    steps:
    - name: generate build image matrix
      id: base-matrix
      run: |
        {
          echo -n "matrix="
          yq -o=json .debian ./base-images.yaml | tr -d '\n'
        } >> "$GITHUB_OUTPUT"

  build_debian:
    needs: gen_debian_base_matrix

    strategy:
      fail-fast: false
      matrix:
        base_tag: ${{ fromJSON(needs.gen_debian_matrix.outputs.base_tag) }}
        arch: ["x64"]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

    - name: get image-name
      id: image-name
      run: |
        src_dir="${{ inputs.context }}"
        src_dir=${src_dir#"./"}
        image_name=${src_dir#"earthly-"}
        echo "image-name: ${image_name}"
        echo "name=${image_name}" >> "$GITHUB_OUTPUT"

    - uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e # v4.4.0
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.name }},enable=true
        flavor: |
          latest=auto
        tags: |
          type=sha
          type=ref,event=pr
          type=raw,value=${{ needs.rust_version.outputs.rust_version }},enable={{is_default_branch}}

    - uses: earthly/actions-setup@135d686cdc4619918fd1b542d0a08d61dd104518 # v1.0.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to ghcr.io
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
      if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push container image
      env:
        EARTHLY_PUSH: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        EARTHLY_REMOTE_CACHE: ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.name }}:cache-${{ matrix.base_tag }}-${{ matrix.arch }}
      working-directory: ${{ inputs.context }}
      run: |
        earthly +docker \
         --BASE_TAG=${{ matrix.base_tag }}  --DOCKER_META_VERSION=${{ steps.meta.outputs.version }}
