name: Build

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMG_NAME: postgres-awscli
  IMG_TAG: 15.2-bullseye

jobs:
  build_img:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e # v4.4.0
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMG_NAME }}
          labels:
            maintainer=sksat
          flavor: |
            latest=auto
          tags: |
            enable={{is_default_branch}},type=raw,value=${{ env.IMG_TAG }}
            prefix=${{ env.IMG_TAG }}-pr-,type=ref,event=pr
            prefix=${{ env.IMG_TAG }}-,type=sha
            prefix=${{ env.IMG_TAG }}-,type=sha,format=long

      - name: Login to ghcr.io
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4.0.0
        with:
          context: ./docker-${{ env.IMG_NAME }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
