name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  gen_docker_matrix:
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

    - name: generate matrix
      id: set-matrix
      run: |
        {
          echo -n "matrix="
          find . -type d -name 'docker-*' | jq -R -s -c 'split("\n")[:-1]'
        } >> "$GITHUB_OUTPUT"

  gen_earthly_debian_matrix:
    name: generate earthly-debian matrix

    outputs:
      context: ${{ steps.context-matrix.outputs.matrix }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

    - name: generate context matrix
      id: context-matrix
      run: |
        {
          echo -n "matrix="
          find . -type d -name 'earthly-debian-*' | jq -R -s -c 'split("\n")[:-1]'
        } >> "$GITHUB_OUTPUT"

  docker:
    name: ${{ matrix.context }}
    needs: gen_docker_matrix
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        context: ${{ fromJSON(needs.gen_docker_matrix.outputs.matrix) }}

    uses: ./.github/workflows/build-docker.yaml
    with:
      context: ${{ matrix.context }}

  earthly_debian:
    name: ${{ matrix.context }}
    needs: gen_earthly_debian_matrix
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        context: ${{ fromJSON(needs.gen_earthly_debian_matrix.outputs.context) }}

    uses: ./.github/workflows/build-earthly-debian.yaml
    with:
      context: ${{ matrix.context }}
