name: docker

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string

env:
  IMG_TAG: 15.2-bullseye

jobs:
  build_img:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: get image name
        id: get_img_name
        run: |
          dir_name=$(basename "${{ inputs.context }}")
          img_name="${dir_name#"docker-"}"
          echo "img_name=${img_name}" >> "$GITHUB_OUTPUT"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@2c0bd771b40637d97bf205cbccdd294a32112176 # v4.5.0
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ steps.get_img_name.outputs.img_name }}
          labels:
            maintainer=sksat
          flavor: |
            latest=auto
          tags: |
            enable={{is_default_branch}},type=raw,value=${{ env.IMG_TAG }}
            enable={{is_default_branch}},prefix=${{ env.IMG_TAG }}-,type=sha
            enable={{is_default_branch}},prefix=${{ env.IMG_TAG }}-,type=sha,format=long
            prefix=${{ env.IMG_TAG }}-pr-,type=ref,event=pr

      - name: Login to ghcr.io
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@44ea916f6c540f9302d50c2b1e5a8dc071f15cdf # v4.1.0
        with:
          context: ${{ inputs.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
