name: docker

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string

env:
  IMG_TAG: 15.2-bullseye

jobs:
  build_img:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: get image name
        id: get_img_name
        run: |
          dir_name=$(basename "${{ inputs.context }}")
          img_name="${dir_name#"docker-"}"
          echo "img_name=${img_name}" >> "$GITHUB_OUTPUT"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@e6428a5c4e294a61438ed7f43155db912025b6b3 # v5.2.0
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ steps.get_img_name.outputs.img_name }}
          labels:
            maintainer=sksat
          flavor: |
            latest=auto
          tags: |
            enable={{is_default_branch}},type=raw,value=${{ env.IMG_TAG }}
            enable={{is_default_branch}},prefix=${{ env.IMG_TAG }}-,type=sha
            enable={{is_default_branch}},prefix=${{ env.IMG_TAG }}-,type=sha,format=long
            prefix=${{ env.IMG_TAG }}-pr-,type=ref,event=pr

      - name: Login to ghcr.io
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4.2.1
        with:
          context: ${{ inputs.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
