name: docker

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string

env:
  IMG_TAG: 15.2-bullseye

jobs:
  build_img:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: get image name
        id: get_img_name
        run: |
          dir_name=$(basename "${{ inputs.context }}")
          img_name="${dir_name#"docker-"}"
          echo "img_name=${img_name}" >> "$GITHUB_OUTPUT"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ steps.get_img_name.outputs.img_name }}
          labels:
            maintainer=sksat
          flavor: |
            latest=auto
          tags: |
            enable={{is_default_branch}},type=raw,value=${{ env.IMG_TAG }}
            enable={{is_default_branch}},prefix=${{ env.IMG_TAG }}-,type=sha
            enable={{is_default_branch}},prefix=${{ env.IMG_TAG }}-,type=sha,format=long
            prefix=${{ env.IMG_TAG }}-pr-,type=ref,event=pr

      - name: Login to ghcr.io
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: ${{ inputs.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
