name: hadolint

on:
  pull_request:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: hadolint
        uses: reviewdog/action-hadolint@0e389972426f8cf0659dd764d1263984098e6d11 # v1.41.0
        with:
          hadolint_ignore: DL3008
          reporter: github-pr-review
          fail_on_error: true
