name: hadolint

on:
  pull_request:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: hadolint
        uses: reviewdog/action-hadolint@0e389972426f8cf0659dd764d1263984098e6d11 # v1.41.0
        with:
          hadolint_ignore: DL3008
          reporter: github-pr-review
          fail_on_error: true
