name: hadolint

on:
  pull_request:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: hadolint
        uses: reviewdog/action-hadolint@v1.34.1
        with:
          hadolint_ignore: DL3008
          reporter: github-pr-review
          fail_on_error: true
