name: hadolint

on:
  pull_request:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: hadolint
        uses: reviewdog/action-hadolint@95bed95955637c5d07d638833a30533c69c0db5c # v1.37.0
        with:
          hadolint_ignore: DL3008
          reporter: github-pr-review
          fail_on_error: true
