name: hadolint

on:
  pull_request:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: hadolint
        uses: reviewdog/action-hadolint@0e389972426f8cf0659dd764d1263984098e6d11 # v1.41.0
        with:
          hadolint_ignore: DL3008
          reporter: github-pr-review
          fail_on_error: true
