name: hadolint

on:
  pull_request:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: hadolint
        uses: reviewdog/action-hadolint@fbda56f005550d67ea4d4950d96571d01313ea17 # v1.36.1
        with:
          hadolint_ignore: DL3008
          reporter: github-pr-review
          fail_on_error: true
