name: validate / renovate.json

on:
  pull_request:
    paths:
      - 'renovate.json5'
      - '.github/workflows/validate-renovate.yaml'

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-renovate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0

      - name: install
        run: |
          npm install -g renovate
      - name: validate
        run: |
          renovate-config-validator

  dry-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0

      - name: Install Renovate CLI
        run: npm install renovate

      - name: Dry-run Renovate
        run: |
          npx renovate '${{ github.repository }}' \
            --dry-run=full \
            --use-base-branch-config=merge
        env:
          # Use the GitHub user of Mend-hosted Renovate
          RENOVATE_USERNAME: renovate[bot]
          RENOVATE_GIT_AUTHOR: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
          RENOVATE_TOKEN: ${{ github.token }}
          # Use renovate.json in the commit `github.sha`.
          RENOVATE_BASE_BRANCHES: ${{ github.sha }}
          LOG_LEVEL: debug
