name: validate / renovate.json

on:
  pull_request:
    paths:
      - 'renovate.json5'
      - '.github/workflows/validate-renovate.yaml'

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-renovate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2

      - name: install
        run: |
          npm install -g renovate
      - name: validate
        run: |
          renovate-config-validator

  dry-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2

      - name: Install Renovate CLI
        run: npm install renovate

      - name: Dry-run Renovate
        run: |
          npx renovate '${{ github.repository }}' \
            --dry-run=full \
            --use-base-branch-config=merge
        env:
          # Use the GitHub user of Mend-hosted Renovate
          RENOVATE_USERNAME: renovate[bot]
          RENOVATE_GIT_AUTHOR: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
          RENOVATE_TOKEN: ${{ github.token }}
          # Use renovate.json in the commit `github.sha`.
          RENOVATE_BASE_BRANCHES: ${{ github.sha }}
          LOG_LEVEL: debug
